# Generated by Django 3.2.5 on 2023-07-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider_song_id', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album_cover', models.URLField()),
                ('year_release_date', models.CharField(max_length=4)),
                ('genres', models.JSONField()),
                ('duration', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
            ],
        ),
    ]
